      name: Build and Push Docker Image

      on:
        push:
          branches:
            - main

      jobs:
        push:
          runs-on: ubuntu-latest

          steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Build, tag, and push image to Docker Hub
              run: |
                docker build -t anatoliyrib/movie-reviews:${{ github.sha }} .
                docker tag anatoliyrib/movie-reviews:${{ github.sha }} anatoliyrib/movie-reviews:latest
                docker push anatoliyrib/movie-reviews:${{ github.sha }}
                docker push anatoliyrib/movie-reviews:latest